import argparse

parser = argparse.ArgumentParser( 
	description="script for importing different test reports into doxygen" 
	)

parser.add_argument( "--html", type=str, default="TestReport.html", 
	           help="HTML file generated by doxygen, containing \"REPLACEME\" tags" )
parser.add_argument( "--env", type=str, nargs="+", default=[],
	           help="environment report file[s]" )
parser.add_argument( "--unit", type=str, nargs="+", default=[],
		   help="junit xml report file[s]" )

args = parser.parse_args()

print( args.env )
print( args.unit )
